export interface AccountRequest {
    LastName: string
    FirstName: string
    Salutation: string
    Type: any
    RecordTypeId: string
    PersonMobilePhone: string
    PersonHomePhone: string
    PersonOtherPhone: string
    PersonBirthdate: string
    Email_c: string
    Trim_Record_Number_c: string
    Trim_URI_c: string
    Alternate_Email_pc: string
    Alternate_Name_pc: string
    Authorised_Representative_Capacity_pc: string
    Authorised_Representative_Email_pc: string
    Authorised_Representative_Name_pc: string
    Authorised_Representative_Phone_Number_pc: string
    City_Of_Birth_pc: string
    Co_Regulator_Jurisdiction_pc: string
    Country_Of_Birth_pc: string
    Country_pc: string
    Date_from_PPP_pc: string
    Date_to_PPP_pc: string
    Education_Provider_pc: string
    End_Date_pc: string
    Interpreter_Required_pc: boolean
    Login_User_ID_pc: string
    PPP_Name_pc: string
    Place_of_Practice_Phone_pc: string
    Place_of_Practice_Type2_pc: string
    Place_of_Practice_Type_pc: string
    Preferred_Communication_Method_pc: string
    Preferred_Contact_Method_After_Hours_pc: string
    Preferred_Contact_Method_Business_Hours_pc: string
    Preferred_Phone_Number_pc: string
    Previous_Legal_Name_pc: string
    Priority_Group_Access_Type_pc: string
    Priority_Group_Access_pc: boolean
    Published_To_Public_Register_pc: boolean
    Qualification_pc: string
    Secondary_Place_of_Practice_Date_To_pc: string
    Secondary_place_of_Practice_Date_from_pc: string
    Secondary_place_of_Practice_Name_pc: string
    Secondary_place_of_Practice_Phone_pc: string
    Sex_pc: string
    Spoken_Languages_pc: string
    Start_Date_pc: string
    State_Of_Birth_pc: string
    State_pc: string
    Student_Id_pc: string
    Unique_Student_Identifier_USI_pc: string
}